In [1]:
import pandas as pd
import numpy as np
import os
import glob
import random

import warnings
warnings.filterwarnings("ignore")

## Baseline

In [2]:
train = pd.read_csv('./data/train/train.csv')

In [3]:
train.tail()

        Day  Hour  Minute  DHI  DNI   WS     RH  T  TARGET
52555  1094    21      30    0    0  2.4  70.70 -4     0.0
52556  1094    22       0    0    0  2.4  66.79 -4     0.0
52557  1094    22      30    0    0  2.2  66.78 -4     0.0
52558  1094    23       0    0    0  2.1  67.72 -4     0.0
52559  1094    23      30    0    0  2.1  67.70 -4     0.0

In [4]:
submission = pd.read_csv('./data/sample_submission.csv')

In [5]:
submission.tail()

,id,q_0.1,q_0.2,q_0.3,q_0.4,q_0.5,q_0.6,q_0.7,q_0.8,q_0.9
7771,80.csv_Day8_21h30m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7772,80.csv_Day8_22h00m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7773,80.csv_Day8_22h30m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7774,80.csv_Day8_23h00m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7775,80.csv_Day8_23h30m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
def cal_ghi(df):
    df['GHI']=0
    for i in range(len(df)):
        hour = df.loc[i,'Hour']
        if 8 <= hour <= 16:
            degree = (hour-7) * np.pi/18
            GHI = df.loc[i,'DNI'] + df.loc[i,'DHI']*(np.cos(90-degree))  # DHI +DNI*cos(Θ)
            if GHI<0:
                GHI=0
            df.loc[i,'GHI']=GHI

In [7]:
# data를 넣어주면 
def preprocess_data(data, is_train=True):
    
    temp = data.copy()
    temp = temp[['Hour', 'TARGET', 'DHI', 'DNI', 'WS', 'RH', 'T']]

    if is_train==True:          
    
        temp['Target1'] = temp['TARGET'].shift(-48).fillna(method='ffill')   # 뒤에서 48개의 값을 지우고 가장 마지막 값으로 채운다
        temp['Target2'] = temp['TARGET'].shift(-48*2).fillna(method='ffill') # 뒤에서 96개의 값을 지우고 가장 마지막 값으로 채운다
        temp = temp.dropna()  # 결측치 제거
        
        return temp.iloc[:-96] # 아 이건 예측값이 0이 되버리니까 제거해버리는구나 ㅇㅋㅇㅋ

    elif is_train==False:
        
        temp = temp[['Hour', 'TARGET', 'DHI', 'DNI', 'WS', 'RH', 'T']]
                              
        return temp.iloc[-48:, :]


df_train = preprocess_data(train)
df_train.iloc[:48]

    Hour     TARGET  DHI  DNI   WS     RH   T    Target1    Target2
0      0   0.000000    0    0  1.5  69.08 -12   0.000000   0.000000
1      0   0.000000    0    0  1.5  69.06 -12   0.000000   0.000000
2      1   0.000000    0    0  1.6  71.78 -12   0.000000   0.000000
3      1   0.000000    0    0  1.6  71.75 -12   0.000000   0.000000
4      2   0.000000    0    0  1.6  75.20 -12   0.000000   0.000000
5      2   0.000000    0    0  1.5  69.29 -11   0.000000   0.000000
6      3   0.000000    0    0  1.5  72.56 -11   0.000000   0.000000
7      3   0.000000    0    0  1.4  72.55 -11   0.000000   0.000000
8      4   0.000000    0    0  1.3  74.62 -11   0.000000   0.000000
9      4   0.000000    0    0  1.3  74.61 -11   0.000000   0.000000
10     5   0.000000    0    0  1.3  73.74 -11   0.000000   0.000000
11     5   0.000000    0    0  1.3  73.73 -11   0.000000   0.000000
12     6   0.000000    0    0  1.4  72.22 -12   0.000000   0.000000
13     6   0.000000    0    0  1.4  72.22 -12   0.000000   0.000000
14     7   0.000000    0    0  1.4  70.27 -12   0.000000   0.000000
15     7   0.000000    0    0  1.6  64.83 -10   0.000000   0.000000
16     8   7.039287   29  494  1.8  65.45  -9   7.133144   0.750808
17     8   5.912871   61    7  1.9  55.90  -7  14.922796   1.689299
18     9  22.337268   58  743  2.1  57.39  -6  22.806037   5.161690
19     9  29.469529   67  811  1.9  53.15  -4   2.158549   4.973992
20    10  25.339762  138  368  1.8  55.99  -3  36.225679  16.517408
21    10  25.152060  178  224  1.9  55.97  -3  41.386914   9.760179
22    11  28.718397  193  261  2.0  58.43  -3  45.140829   7.601678
23    11  33.129393  189  364  2.3  58.41  -3  47.580874  10.980202
24    12  19.427151  190   37  2.6  59.19  -3  48.612666  17.361857
25    12  25.715166  213  133  2.9  59.18  -3  48.143432   4.880090
26    13  24.589225  211  114  3.2  63.27  -4  46.172141  13.326545
27    13  21.304405  185  101  3.1  63.27  -4  42.794162   9.478740
28    14  11.731500  124    2  3.0  62.84  -4  38.195666   4.504797
29    14  14.734764  135   69  2.7  62.85  -4  32.283670   2.627827
30    15   5.818888   62    0  2.5  68.55  -5  25.432775  14.265504
31    15   7.602096   73   39  2.2  68.55  -5  17.737444  16.611987
32    16   4.035725   41   11  2.0  70.27  -6   9.854244   9.010089
33    16   0.938541   10    0  2.0  70.28  -6   2.627827   2.440259
34    17   0.000000    0    0  2.0  71.33  -7   0.000000   0.000000
35    17   0.000000    0    0  2.0  71.35  -7   0.000000   0.000000
36    18   0.000000    0    0  2.1  76.43  -8   0.000000   0.000000
37    18   0.000000    0    0  2.2  76.44  -8   0.000000   0.000000
38    19   0.000000    0    0  2.3  76.72  -8   0.000000   0.000000
39    19   0.000000    0    0  2.2  76.72  -8   0.000000   0.000000
40    20   0.000000    0    0  2.2  77.51  -8   0.000000   0.000000
41    20   0.000000    0    0  2.0  77.51  -8   0.000000   0.000000
42    21   0.000000    0    0  1.9  83.46  -9   0.000000   0.000000
43    21   0.000000    0    0  1.8  83.46  -9   0.000000   0.000000
44    22   0.000000    0    0  1.8  83.36  -9   0.000000   0.000000
45    22   0.000000    0    0  1.7  83.36  -9   0.000000   0.000000
46    23   0.000000    0    0  1.7  90.86 -10   0.000000   0.000000
47    23   0.000000    0    0  1.6  90.85 -10   0.000000   0.000000

In [8]:
train.iloc[48:96]

    Day  Hour  Minute  DHI  DNI   WS     RH   T     TARGET
48    1     0       0    0    0  1.6  90.66 -10   0.000000
49    1     0      30    0    0  1.6  90.68 -10   0.000000
50    1     1       0    0    0  1.6  88.11 -11   0.000000
51    1     1      30    0    0  1.6  88.11 -11   0.000000
52    1     2       0    0    0  1.6  90.85 -11   0.000000
53    1     2      30    0    0  1.6  90.84 -11   0.000000
54    1     3       0    0    0  1.7  93.78 -12   0.000000
55    1     3      30    0    0  1.7  93.77 -12   0.000000
56    1     4       0    0    0  1.7  90.46 -12   0.000000
57    1     4      30    0    0  1.6  90.46 -12   0.000000
58    1     5       0    0    0  1.6  87.34 -12   0.000000
59    1     5      30    0    0  1.6  87.34 -12   0.000000
60    1     6       0    0    0  1.7  84.96 -12   0.000000
61    1     6      30    0    0  1.7  84.96 -12   0.000000
62    1     7       0    0    0  1.8  83.20 -12   0.000000
63    1     7      30    0    0  2.0  70.75 -10   0.000000
64    1     8       0   27  519  2.3  73.26  -9   7.133144
65    1     8      30   41  690  2.8  57.87  -6  14.922796
66    1     9       0   49  799  3.3  66.23  -4  22.806037
67    1     9      30   23    0  3.0  56.92  -2   2.158549
68    1    10       0   60  910  2.7  57.91  -1  36.225679
69    1    10      30   64  938  2.4  53.78   0  41.386914
70    1    11       0   66  961  2.1  59.87   0  45.140829
71    1    11      30   67  972  1.9  55.63   0  47.580874
72    1    12       0   67  980  1.7  58.88   1  48.612666
73    1    12      30   66  978  1.5  58.86   1  48.143432
74    1    13       0   64  972  1.4  60.68   2  46.172141
75    1    13      30   62  958  1.2  60.66   1  42.794162
76    1    14       0   57  936  1.2  61.34   1  38.195666
77    1    14      30   53  902  0.9  61.33   0  32.283670
78    1    15       0   46  852  0.6  72.29   0  25.432775
79    1    15      30   39  772  0.5  77.79  -1  17.737444
80    1    16       0   28  641  0.5  68.91  -2   9.854244
81    1    16      30   14  389  0.4  74.29  -3   2.627827
82    1    17       0    0    0  0.4  67.81  -4   0.000000
83    1    17      30    0    0  0.8  73.20  -5   0.000000
84    1    18       0    0    0  1.3  73.62  -6   0.000000
85    1    18      30    0    0  1.5  73.60  -6   0.000000
86    1    19       0    0    0  1.8  74.97  -7   0.000000
87    1    19      30    0    0  2.0  74.95  -7   0.000000
88    1    20       0    0    0  2.2  71.27  -8   0.000000
89    1    20      30    0    0  2.2  71.26  -8   0.000000
90    1    21       0    0    0  2.2  74.50  -8   0.000000
91    1    21      30    0    0  2.2  74.50  -8   0.000000
92    1    22       0    0    0  2.2  72.83  -8   0.000000
93    1    22      30    0    0  2.2  72.82  -8   0.000000
94    1    23       0    0    0  2.2  72.51  -8   0.000000
95    1    23      30    0    0  2.2  72.49  -8   0.000000

In [9]:
train.iloc[48+48:96+48]

     Day  Hour  Minute  DHI  DNI   WS     RH   T     TARGET
96     2     0       0    0    0  2.2  73.80  -8   0.000000
97     2     0      30    0    0  2.1  68.20  -8   0.000000
98     2     1       0    0    0  2.1  69.06  -8   0.000000
99     2     1      30    0    0  2.1  69.04  -8   0.000000
100    2     2       0    0    0  2.2  69.38  -8   0.000000
101    2     2      30    0    0  2.2  69.36  -7   0.000000
102    2     3       0    0    0  2.2  70.03  -7   0.000000
103    2     3      30    0    0  2.2  70.02  -7   0.000000
104    2     4       0    0    0  2.3  72.18  -7   0.000000
105    2     4      30    0    0  2.4  66.78  -7   0.000000
106    2     5       0    0    0  2.5  68.32  -7   0.000000
107    2     5      30    0    0  2.5  68.32  -7   0.000000
108    2     6       0    0    0  2.6  69.68  -7   0.000000
109    2     6      30    0    0  2.6  69.69  -6   0.000000
110    2     7       0    0    0  2.6  74.08  -6   0.000000
111    2     7      30    0    0  2.4  63.54  -4   0.000000
112    2     8       0    8    0  2.2  72.05  -3   0.750808
113    2     8      30   18    0  2.0  66.85  -2   1.689299
114    2     9       0   55    0  1.8  72.81  -1   5.161690
115    2     9      30   53    0  2.0  67.63  -1   4.973992
116    2    10       0  153   65  2.2  72.03  -1  16.517408
117    2    10      30  104    0  2.6  72.02   0   9.760179
118    2    11       0   81    0  3.1  75.29   0   7.601678
119    2    11      30  117    0  3.5  75.28   0  10.980202
120    2    12       0  176   20  3.9  75.99   0  17.361857
121    2    12      30   52    0  4.3  76.01   0   4.880090
122    2    13       0  141    3  4.7  79.12  -1  13.326545
123    2    13      30  101    0  5.0  79.17  -1   9.478740
124    2    14       0   48    0  5.3  78.49  -2   4.504797
125    2    14      30   28    0  5.1  84.71  -3   2.627827
126    2    15       0  110  157  5.1  80.48  -4  14.265504
127    2    15      30   71  535  4.4  86.96  -5  16.611987
128    2    16       0   47  403  3.7  79.93  -7   9.010089
129    2    16      30   26    0  3.1  86.46  -8   2.440259
130    2    17       0    0    0  2.6  80.46  -9   0.000000
131    2    17      30    0    0  2.3  87.15  -9   0.000000
132    2    18       0    0    0  2.0  85.23 -10   0.000000
133    2    18      30    0    0  1.7  85.26 -10   0.000000
134    2    19       0    0    0  1.5  85.29 -11   0.000000
135    2    19      30    0    0  1.2  85.30 -11   0.000000
136    2    20       0    0    0  0.9  86.81 -12   0.000000
137    2    20      30    0    0  0.7  86.81 -12   0.000000
138    2    21       0    0    0  0.5  82.90 -12   0.000000
139    2    21      30    0    0  0.4  82.89 -12   0.000000
140    2    22       0    0    0  0.4  79.09 -13   0.000000
141    2    22      30    0    0  0.7  79.08 -13   0.000000
142    2    23       0    0    0  1.1  81.09 -13   0.000000
143    2    23      30    0    0  1.4  81.08 -13   0.000000

In [10]:
df_train.tail()

       Hour  TARGET  DHI  DNI   WS     RH  T  Target1  Target2
52459    21     0.0    0    0  3.5  55.97 -1      0.0      0.0
52460    22     0.0    0    0  3.9  54.23 -2      0.0      0.0
52461    22     0.0    0    0  4.1  54.21 -2      0.0      0.0
52462    23     0.0    0    0  4.3  56.46 -2      0.0      0.0
52463    23     0.0    0    0  4.1  56.44 -2      0.0      0.0

In [11]:
cal_ghi(df_train)

In [12]:
df_train = df_train[['Hour', 'TARGET', 'DHI', 'DNI', 'WS', 'RH', 'T','GHI','Target1','Target2']]

In [13]:
df_test = []

for i in range(81):
    file_path = './data/test/' + str(i) + '.csv'
    temp = pd.read_csv(file_path)
    temp = preprocess_data(temp, is_train=False)
    df_test.append(temp)

X_test = pd.concat(df_test)
X_test.shape

(3888, 7)

In [14]:
df_train.head()

   Hour  TARGET  DHI  DNI   WS     RH   T  GHI  Target1  Target2
0     0     0.0    0    0  1.5  69.08 -12  0.0      0.0      0.0
1     0     0.0    0    0  1.5  69.06 -12  0.0      0.0      0.0
2     1     0.0    0    0  1.6  71.78 -12  0.0      0.0      0.0
3     1     0.0    0    0  1.6  71.75 -12  0.0      0.0      0.0
4     2     0.0    0    0  1.6  75.20 -12  0.0      0.0      0.0

In [15]:
X_test.head()

     Hour  TARGET  DHI  DNI   WS     RH    T
288     0     0.0    0    0  0.8  80.92 -2.8
289     0     0.0    0    0  0.9  81.53 -2.9
290     1     0.0    0    0  1.0  79.91 -3.0
291     1     0.0    0    0  0.9  79.91 -3.0
292     2     0.0    0    0  0.9  77.20 -3.0

In [16]:
X_test['GHI']=0
for i in range(len(X_test)):
    hour = X_test.iloc[i,0] #hour
    if 8 <= hour <= 16:
        degree = (hour-7) * np.pi/18
        GHI = X_test.iloc[i,3] + X_test.iloc[i,2]*(np.cos(90-degree))  # DHI +DNI*cos(Θ)
        if GHI<0:
            GHI=0
        X_test.iloc[i,7]=GHI
X_test = X_test[['Hour', 'TARGET', 'DHI', 'DNI', 'WS', 'RH', 'T','GHI']]

In [17]:
X_test.head(48)

     Hour     TARGET  DHI  DNI   WS     RH    T         GHI
288     0   0.000000    0    0  0.8  80.92 -2.8    0.000000
289     0   0.000000    0    0  0.9  81.53 -2.9    0.000000
290     1   0.000000    0    0  1.0  79.91 -3.0    0.000000
291     1   0.000000    0    0  0.9  79.91 -3.0    0.000000
292     2   0.000000    0    0  0.9  77.20 -3.0    0.000000
293     2   0.000000    0    0  1.1  78.36 -3.2    0.000000
294     3   0.000000    0    0  1.2  76.78 -3.4    0.000000
295     3   0.000000    0    0  1.8  77.93 -3.6    0.000000
296     4   0.000000    0    0  2.4  76.89 -3.8    0.000000
297     4   0.000000    0    0  2.9  78.64 -4.1    0.000000
298     5   0.000000    0    0  3.5  77.21 -4.3    0.000000
299     5   0.000000    0    0  3.6  79.07 -4.6    0.000000
300     6   0.000000    0    0  3.8  74.74 -4.9    0.000000
301     6   0.000000    0    0  3.9  76.45 -5.2    0.000000
302     7   0.000000    0    0  4.1  69.45 -5.5    0.000000
303     7   0.469267    5    0  4.5  68.92 -5.4    0.000000
304     8   1.877069   20    0  5.0  63.50 -5.4    0.000000
305     8   3.191010   34    0  5.3  62.54 -5.2    0.000000
306     9   4.692657   50    1  5.6  61.26 -5.1    0.000000
307     9   6.382006   66    7  5.8  60.80 -5.0    0.000000
308    10  12.576279  119   41  5.9  60.54 -4.8   48.015668
309    10  15.954963  142   71  6.0  60.08 -4.7   79.371638
310    11  13.890188  137   26  6.1  59.66 -4.6   57.702577
311    11  10.886904  108   18  6.1  59.66 -4.6   42.991813
312    12  11.356167  111   23  6.2  59.63 -4.6   67.047576
313    12  14.453320  137   38  6.3  60.08 -4.7   92.365026
314    13  12.200868  117   29  6.4  60.25 -4.8   93.371881
315    13   7.695957   78    9  6.5  61.64 -5.1   51.914587
316    14   9.573041   93   24  6.6  61.52 -5.3   87.875363
317    14  10.605451  104   30  6.5  62.46 -5.5  101.430514
318    15  10.230059   99   40  6.5  61.50 -5.7  119.458160
319    15   6.757493   68   22  6.3  63.00 -6.0   76.577322
320    16   3.754175   38   16  6.0  62.02 -6.3   49.971873
321    16   0.938544   10    5  6.0  62.02 -6.3   13.939967
322    17   0.000000    0    0  5.4  61.99 -6.8    0.000000
323    17   0.000000    0    0  5.1  62.46 -6.9    0.000000
324    18   0.000000    0    0  4.9  60.98 -7.1    0.000000
325    18   0.000000    0    0  4.7  61.45 -7.2    0.000000
326    19   0.000000    0    0  4.5  59.31 -7.3    0.000000
327    19   0.000000    0    0  4.3  59.77 -7.4    0.000000
328    20   0.000000    0    0  4.1  57.30 -7.5    0.000000
329    20   0.000000    0    0  4.0  58.20 -7.7    0.000000
330    21   0.000000    0    0  3.8  55.23 -7.8    0.000000
331    21   0.000000    0    0  3.6  56.09 -8.0    0.000000
332    22   0.000000    0    0  3.4  53.54 -8.2    0.000000
333    22   0.000000    0    0  3.4  53.89 -8.3    0.000000
334    23   0.000000    0    0  3.4  51.96 -8.4    0.000000
335    23   0.000000    0    0  3.4  51.96 -8.4    0.000000

In [18]:
df_train.head()

   Hour  TARGET  DHI  DNI   WS     RH   T  GHI  Target1  Target2
0     0     0.0    0    0  1.5  69.08 -12  0.0      0.0      0.0
1     0     0.0    0    0  1.5  69.06 -12  0.0      0.0      0.0
2     1     0.0    0    0  1.6  71.78 -12  0.0      0.0      0.0
3     1     0.0    0    0  1.6  71.75 -12  0.0      0.0      0.0
4     2     0.0    0    0  1.6  75.20 -12  0.0      0.0      0.0

In [19]:
df_train.iloc[-48:]

,Hour,TARGET,DHI,DNI,WS,RH,T,GHI,Target1,Target2
52416,0,0.000000,0,0,3.4,50.47,-1,0.000000,0.000000,0.000000
52417,0,0.000000,0,0,3.4,50.45,0,0.000000,0.000000,0.000000
52418,1,0.000000,0,0,3.5,50.30,0,0.000000,0.000000,0.000000
52419,1,0.000000,0,0,3.5,50.30,0,0.000000,0.000000,0.000000
52420,2,0.000000,0,0,3.5,51.14,0,0.000000,0.000000,0.000000
52421,2,0.000000,0,0,3.5,51.12,0,0.000000,0.000000,0.000000
52422,3,0.000000,0,0,3.6,52.09,0,0.000000,0.000000,0.000000
52423,3,0.000000,0,0,3.7,48.39,0,0.000000,0.000000,0.000000
52424,4,0.000000,0,0,3.8,49.00,0,0.000000,0.000000,0.000000
52425,4,0.000000,0,0,3.9,49.00,0,0.000000,0.000000,0.000000
52426,5,0.000000,0,0,4.0,49.24,0,0.000000,0.000000,0.000000
52427,5,0.000000,0,0,4.2,49.24,0,0.000000,0.000000,0.000000
52428,6,0.000000,0,0,4.4,49.16,0,0.000000,0.000000,0.000000
52429,6,0.000000,0,0,4.6,45.71,0,0.000000,0.000000,0.000000
52430,7,0.000000,0,0,4.8,45.96,0,0.000000,0.000000,0.000000
52431,7,0.000000,0,0,5.0,45.96,1,0.000000,0.000000,0.000000
52432,8,5.536903,32,284,5.3,45.18,2,274.847185,7.320054,5.349564
52433,8,11.449064,54,392,5.4,42.07,3,376.554624,15.015330,11.168266
52434,9,17.267061,77,441,5.5,43.19,5,432.122932,22.710188,17.174539
52435,9,22.709689,99,469,5.2,40.26,6,457.586626,29.748142,22.617587
52436,10,27.401472,119,487,4.9,43.22,7,494.015668,35.753684,27.403580
52437,10,33.688796,102,645,4.9,40.33,7,651.013430,40.633005,31.532887
52438,11,36.878973,111,658,4.9,41.44,8,683.686030,44.197978,35.474498
52439,11,42.697030,69,860,4.5,41.43,8,875.966992,43.728785,39.322261
52440,12,43.353431,72,856,4.1,42.34,9,884.571401,42.133066,37.257198
52441,12,38.473824,125,631,3.6,42.34,9,680.603126,46.731107,37.538738
52442,13,30.685221,185,326,3.1,41.73,9,427.784597,44.760518,35.943342
52443,13,29.934841,159,394,2.7,44.69,8,481.479735,41.382820,15.015660
52444,14,26.650454,138,399,2.4,46.92,8,493.782797,36.690891,29.468234
52445,14,22.334077,113,396,1.9,50.31,7,473.612001,30.873576,24.869688
52446,15,17.360713,88,380,1.4,50.46,6,450.629476,24.117314,19.426511
52447,15,11.918157,62,346,1.2,58.13,4,395.761676,16.610162,17.080689
52448,16,6.287600,39,258,1.1,53.35,3,292.865870,8.915156,9.197496
52449,16,1.407687,15,0,1.0,57.35,2,13.409950,2.158430,2.252448
52450,17,0.000000,0,0,0.9,52.70,2,0.000000,0.000000,0.000000
52451,17,0.000000,0,0,1.0,52.71,1,0.000000,0.000000,0.000000
52452,18,0.000000,0,0,1.2,50.32,1,0.000000,0.000000,0.000000
52453,18,0.000000,0,0,1.4,50.32,0,0.000000,0.000000,0.000000
52454,19,0.000000,0,0,1.7,51.78,0,0.000000,0.000000,0.000000
52455,19,0.000000,0,0,1.9,51.77,0,0.000000,0.000000,0.000000
52456,20,0.000000,0,0,2.1,53.88,0,0.000000,0.000000,0.000000
52457,20,0.000000,0,0,2.6,53.87,0,0.000000,0.000000,0.000000
52458,21,0.000000,0,0,3.1,55.98,-1,0.000000,0.000000,0.000000
52459,21,0.000000,0,0,3.5,55.97,-1,0.000000,0.000000,0.000000
52460,22,0.000000,0,0,3.9,54.23,-2,0.000000,0.000000,0.000000
52461,22,0.000000,0,0,4.1,54.21,-2,0.000000,0.000000,0.000000
52462,23,0.000000,0,0,4.3,56.46,-2,0.000000,0.000000,0.000000
52463,23,0.000000,0,0,4.1,56.44,-2,0.000000,0.000000,0.000000

In [20]:
df_train = df_train.drop(['DHI','DNI'],axis=1)
X_test = X_test.drop(['DHI','DNI'],axis=1)

In [21]:
df_train.columns

Index(['Hour', 'TARGET', 'WS', 'RH', 'T', 'GHI', 'Target1', 'Target2'], dtype='object')

In [22]:
df_train = df_train.drop(['Hour','WS','RH','T'],axis=1)
X_test = X_test.drop(['Hour','WS','RH','T'],axis=1)

In [23]:
X_test

     TARGET  GHI
288     0.0  0.0
289     0.0  0.0
290     0.0  0.0
291     0.0  0.0
292     0.0  0.0
..      ...  ...
331     0.0  0.0
332     0.0  0.0
333     0.0  0.0
334     0.0  0.0
335     0.0  0.0

[3888 rows x 2 columns]

In [24]:
from sklearn.model_selection import train_test_split
X_train_1, X_valid_1, Y_train_1, Y_valid_1 = train_test_split(df_train.iloc[:, :-2], df_train.iloc[:, -2], test_size=0.3, random_state=0)
X_train_2, X_valid_2, Y_train_2, Y_valid_2 = train_test_split(df_train.iloc[:, :-2], df_train.iloc[:, -1], test_size=0.3, random_state=0)

In [25]:
X_train_1.tail(48)

          TARGET          GHI
19129  38.761729   371.158627
16321   0.000000     0.000000
24999   0.000000     0.000000
15246  27.024624   898.117346
3219    0.000000     0.000000
49811   0.000000     0.000000
797    24.868868   419.337948
33523  35.381039   932.235670
31921   0.000000     0.000000
42968   0.000000     0.000000
24675   0.000000     0.000000
47954   0.000000     0.000000
2496    0.000000     0.000000
7599   47.946252     0.000000
1871    0.000000     0.000000
18430   0.000000     0.000000
7877    0.000000     0.000000
37619   0.281562     0.000000
5072   15.484219   152.039466
2163    0.000000     0.000000
38804  37.812382   138.160439
6921    0.000000     0.000000
38984   0.000000     0.000000
27469  21.861509     0.000000
16921  34.814119   522.666601
35665   0.000000     0.000000
24152   0.000000     0.000000
51374   0.000000     0.000000
43095   0.000000     0.000000
18983  11.730985    28.925709
32230  58.081621  1012.115746
17089   0.000000     0.000000
14650   0.000000     0.000000
39512   0.000000     0.000000
48600  65.683407   847.079301
15430  53.397095  1009.429803
14935   0.000000     0.000000
46884   1.501236     0.000000
20757  67.283012   971.364923
41993   0.000000     0.000000
32103   0.000000     0.000000
30403  60.706898   948.621657
21243  52.648659   477.067325
45891   0.000000     0.000000
52416   0.000000     0.000000
42613   9.664419     0.000000
43567  65.014422   910.759860
2732    0.000000     0.000000

In [26]:
X_train_1.head()

          TARGET         GHI
32908   1.783051   13.049805
10140  12.103848    0.000000
32182  56.300682  946.818237
20953  65.401188  648.015752
36079  19.614206  592.182538

In [27]:
X_test.head()

     TARGET  GHI
288     0.0  0.0
289     0.0  0.0
290     0.0  0.0
291     0.0  0.0
292     0.0  0.0

In [28]:
X_test.head()

     TARGET  GHI
288     0.0  0.0
289     0.0  0.0
290     0.0  0.0
291     0.0  0.0
292     0.0  0.0

In [32]:
quantiles = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

In [33]:
from lightgbm import LGBMRegressor

# Get the model and the predictions in (a) - (b)
def LGBM(q, X_train, Y_train, X_valid, Y_valid, X_test):
    
    # (a) Modeling  
    model = LGBMRegressor(objective='quantile', alpha=q,
                         n_estimators=10000, bagging_fraction=0.7, learning_rate=0.027, subsample=0.7)                   
                         
                         
    model.fit(X_train, Y_train, eval_metric = ['quantile'], 
          eval_set=[(X_valid, Y_valid)], early_stopping_rounds=300, verbose=500)

    # (b) Predictions
    pred = pd.Series(model.predict(X_test).round(2))
    return pred, model

In [34]:
# Target 예측

def train_data(X_train, Y_train, X_valid, Y_valid, X_test):

    LGBM_models=[]
    LGBM_actual_pred = pd.DataFrame()

    for q in quantiles:
        print(q)
        pred , model = LGBM(q, X_train, Y_train, X_valid, Y_valid, X_test)
        LGBM_models.append(model)
        LGBM_actual_pred = pd.concat([LGBM_actual_pred,pred],axis=1)

    LGBM_actual_pred.columns=quantiles
    
    return LGBM_models, LGBM_actual_pred

In [35]:
# Target1
models_1, results_1 = train_data(X_train_1, Y_train_1, X_valid_1, Y_valid_1, X_test)
results_1.sort_index()[:48]

0.1
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
Early stopping, best iteration is:
[91]	valid_0's quantile: 1.45668
0.2
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
Early stopping, best iteration is:
[129]	valid_0's quantile: 2.36278
0.3
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
Early stopping, best iteration is:
[181]	valid_0's quantile: 2.81087
0.4
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
[500]	valid_0's quantile: 2.94861
Early stopping, best iteration is:
[222]	valid_0's quantile: 2.93696
0.5
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
[500]	valid_0's quantile: 2.85568
Early stopping, best iteration is:
[261]	valid_0's quantile: 2.84832
0.6
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
[500]	valid_0's quantile: 2.61713
Early stopping, best iteration is:
[277]	valid_0's quantile: 2.61197
0.7
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
[500]	valid_0's quantile: 2.25891
Early stopping, best iteration is:
[321]	valid_0's quantile: 2.25701
0.8
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
[500]	valid_0's quantile: 1.75877
Early stopping, best iteration is:
[481]	valid_0's quantile: 1.75869
0.9
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
[500]	valid_0's quantile: 1.07449
Early stopping, best iteration is:
[474]	valid_0's quantile: 1.07392

      0.1    0.2    0.3    0.4    0.5    0.6    0.7    0.8    0.9
0    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
1    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
2    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
3    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
4    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
5    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
6    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
7    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
8    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
9    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
10   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
11   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
12   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
13   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
14   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
15   0.24   0.75   1.13   1.59   2.26   3.89   6.68  10.42  20.07
16   0.40   1.22   1.61   1.79   2.08   2.65   3.87   5.35  12.52
17   1.38   2.44   2.70   3.01   3.26   3.36   4.76   6.65  17.53
18   1.58   3.35   4.41   4.77   5.25   6.70   8.85  11.68  21.77
19   1.79   4.13   5.65   6.20   6.61   8.34  11.33  17.07  22.83
20  11.56  20.26  29.64  35.86  43.12  48.65  55.91  65.86  82.81
21  13.66  20.52  27.65  30.90  39.70  46.85  52.56  64.18  87.18
22  13.12  21.91  29.05  36.27  41.94  48.65  54.22  69.79  80.47
23  10.55  17.70  24.65  30.47  38.70  46.86  53.78  57.77  72.48
24  10.55  19.98  27.04  32.45  41.19  46.20  53.41  66.23  85.21
25  13.66  22.60  31.61  35.75  42.32  48.75  60.55  69.16  85.80
26  11.27  21.00  27.76  31.41  39.01  44.25  48.75  53.24  69.69
27   5.60  11.13  16.30  22.50  26.76  33.34  40.26  46.24  61.08
28   6.03  15.04  18.07  23.43  28.68  30.23  34.86  45.24  54.10
29   2.56   4.91  10.20  14.77  19.06  23.02  24.11  30.85  39.52
30   2.67   6.65  10.78  14.85  17.75  20.63  23.85  30.12  37.26
31   2.25   5.74   7.81  12.19  15.57  14.28  20.28  26.55  39.77
32   3.07   4.70   7.11   9.69  13.06  13.72  22.85  30.42  53.22
33   0.98   2.46   4.59   9.74  14.01  22.13  26.74  38.64  50.10
34   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
35   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
36   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
37   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
38   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
39   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
40   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
41   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
42   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
43   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
44   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
45   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
46   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
47   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00

In [36]:
# Target2
models_2, results_2 = train_data(X_train_2, Y_train_2, X_valid_2, Y_valid_2, X_test)
results_2.sort_index()[:48]

0.1
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
Early stopping, best iteration is:
[136]	valid_0's quantile: 1.47208
0.2
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
[500]	valid_0's quantile: 2.40072
Early stopping, best iteration is:
[253]	valid_0's quantile: 2.38952
0.3
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
[500]	valid_0's quantile: 2.87877
Early stopping, best iteration is:
[226]	valid_0's quantile: 2.86344
0.4
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
[500]	valid_0's quantile: 3.0084
Early stopping, best iteration is:
[238]	valid_0's quantile: 2.99554
0.5
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
[500]	valid_0's quantile: 2.93617
Early stopping, best iteration is:
[281]	valid_0's quantile: 2.92691
0.6
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
[500]	valid_0's quantile: 2.70794
Early stopping, best iteration is:
[289]	valid_0's quantile: 2.7058
0.7
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
[500]	valid_0's quantile: 2.33552
Early stopping, best iteration is:
[369]	valid_0's quantile: 2.33344
0.8
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
[500]	valid_0's quantile: 1.8173
Early stopping, best iteration is:
[429]	valid_0's quantile: 1.81693
0.9
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=0.7 will be ignored. Current value: bagging_fraction=0.7
Training until validation scores don't improve for 300 rounds
[500]	valid_0's quantile: 1.11411
Early stopping, best iteration is:
[357]	valid_0's quantile: 1.11353

      0.1    0.2    0.3    0.4    0.5    0.6    0.7    0.8    0.9
0    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
1    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
2    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
3    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
4    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
5    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
6    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
7    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
8    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
9    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
10   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
11   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
12   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
13   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
14   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
15   0.29   0.83   1.50   2.26   3.92   5.94  10.47  15.05  23.72
16   0.31   1.00   1.46   1.78   2.12   2.68   3.83   8.11  15.25
17   1.01   2.19   2.66   2.86   3.21   3.56   4.82   6.92  16.72
18   1.31   2.89   4.14   4.52   5.16   6.61   8.88  13.24  24.93
19   1.81   3.85   5.43   6.21   6.91   8.10  14.00  21.24  28.60
20  16.13  25.24  32.92  37.56  45.89  51.14  57.32  72.05  84.80
21  14.65  25.33  32.52  40.07  47.76  53.02  60.76  67.48  81.01
22  16.15  27.07  33.47  39.31  45.41  53.78  58.88  70.10  81.68
23  13.81  22.96  30.64  38.26  44.82  50.11  54.88  64.81  82.63
24  12.18  22.23  31.16  39.32  45.96  49.20  54.65  67.53  76.32
25  11.79  21.03  26.32  32.84  40.21  47.92  57.70  69.41  82.41
26  10.03  13.43  20.30  26.64  34.38  38.09  47.49  57.68  70.35
27   4.07   8.92  18.55  28.75  35.43  42.97  53.82  66.72  76.23
28   8.90  17.19  26.41  27.51  32.80  36.36  51.60  54.55  63.71
29   6.68  11.19  16.64  21.02  29.23  37.50  44.28  41.54  51.70
30   4.84   9.21  13.63  16.98  18.57  22.65  23.80  24.92  42.74
31   3.95   5.30  11.32  14.24  18.02  19.19  26.24  32.93  45.60
32   1.47   3.51   6.94  10.01  14.80  20.60  29.90  34.62  49.35
33   1.84   5.09   7.21  14.91  24.25  29.54  35.09  42.30  49.60
34   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
35   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
36   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
37   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
38   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
39   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
40   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
41   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
42   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
43   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
44   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
45   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
46   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
47   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00

In [37]:
results_1.sort_index().iloc[:48]

      0.1    0.2    0.3    0.4    0.5    0.6    0.7    0.8    0.9
0    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
1    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
2    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
3    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
4    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
5    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
6    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
7    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
8    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
9    0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
10   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
11   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
12   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
13   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
14   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
15   0.24   0.75   1.13   1.59   2.26   3.89   6.68  10.42  20.07
16   0.40   1.22   1.61   1.79   2.08   2.65   3.87   5.35  12.52
17   1.38   2.44   2.70   3.01   3.26   3.36   4.76   6.65  17.53
18   1.58   3.35   4.41   4.77   5.25   6.70   8.85  11.68  21.77
19   1.79   4.13   5.65   6.20   6.61   8.34  11.33  17.07  22.83
20  11.56  20.26  29.64  35.86  43.12  48.65  55.91  65.86  82.81
21  13.66  20.52  27.65  30.90  39.70  46.85  52.56  64.18  87.18
22  13.12  21.91  29.05  36.27  41.94  48.65  54.22  69.79  80.47
23  10.55  17.70  24.65  30.47  38.70  46.86  53.78  57.77  72.48
24  10.55  19.98  27.04  32.45  41.19  46.20  53.41  66.23  85.21
25  13.66  22.60  31.61  35.75  42.32  48.75  60.55  69.16  85.80
26  11.27  21.00  27.76  31.41  39.01  44.25  48.75  53.24  69.69
27   5.60  11.13  16.30  22.50  26.76  33.34  40.26  46.24  61.08
28   6.03  15.04  18.07  23.43  28.68  30.23  34.86  45.24  54.10
29   2.56   4.91  10.20  14.77  19.06  23.02  24.11  30.85  39.52
30   2.67   6.65  10.78  14.85  17.75  20.63  23.85  30.12  37.26
31   2.25   5.74   7.81  12.19  15.57  14.28  20.28  26.55  39.77
32   3.07   4.70   7.11   9.69  13.06  13.72  22.85  30.42  53.22
33   0.98   2.46   4.59   9.74  14.01  22.13  26.74  38.64  50.10
34   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
35   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
36   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
37   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
38   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
39   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
40   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
41   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
42   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
43   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
44   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
45   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
46   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
47   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00

In [38]:
results_2.sort_index()

      0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...
3883  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3884  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3885  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3886  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3887  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[3888 rows x 9 columns]

In [39]:
print(results_1.shape, results_2.shape)

(3888, 9) (3888, 9)

In [40]:
submission.loc[submission.id.str.contains("Day7"), "q_0.1":] = results_1.sort_index().values
submission.loc[submission.id.str.contains("Day8"), "q_0.1":] = results_2.sort_index().values
submission

,id,q_0.1,q_0.2,q_0.3,q_0.4,q_0.5,q_0.6,q_0.7,q_0.8,q_0.9
0,0.csv_Day7_0h00m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.csv_Day7_0h30m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.csv_Day7_1h00m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.csv_Day7_1h30m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.csv_Day7_2h00m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
7771,80.csv_Day8_21h30m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7772,80.csv_Day8_22h00m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7773,80.csv_Day8_22h30m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7774,80.csv_Day8_23h00m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7775,80.csv_Day8_23h30m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [41]:
submission.iloc[:48]

,id,q_0.1,q_0.2,q_0.3,q_0.4,q_0.5,q_0.6,q_0.7,q_0.8,q_0.9
0,0.csv_Day7_0h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,0.csv_Day7_0h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,0.csv_Day7_1h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,0.csv_Day7_1h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,0.csv_Day7_2h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
5,0.csv_Day7_2h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
6,0.csv_Day7_3h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
7,0.csv_Day7_3h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
8,0.csv_Day7_4h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
9,0.csv_Day7_4h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
10,0.csv_Day7_5h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
11,0.csv_Day7_5h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
12,0.csv_Day7_6h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
13,0.csv_Day7_6h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
14,0.csv_Day7_7h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
15,0.csv_Day7_7h30m,0.24,0.75,1.13,1.59,2.26,3.89,6.68,10.42,20.07
16,0.csv_Day7_8h00m,0.40,1.22,1.61,1.79,2.08,2.65,3.87,5.35,12.52
17,0.csv_Day7_8h30m,1.38,2.44,2.70,3.01,3.26,3.36,4.76,6.65,17.53
18,0.csv_Day7_9h00m,1.58,3.35,4.41,4.77,5.25,6.70,8.85,11.68,21.77
19,0.csv_Day7_9h30m,1.79,4.13,5.65,6.20,6.61,8.34,11.33,17.07,22.83
20,0.csv_Day7_10h00m,11.56,20.26,29.64,35.86,43.12,48.65,55.91,65.86,82.81
21,0.csv_Day7_10h30m,13.66,20.52,27.65,30.90,39.70,46.85,52.56,64.18,87.18
22,0.csv_Day7_11h00m,13.12,21.91,29.05,36.27,41.94,48.65,54.22,69.79,80.47
23,0.csv_Day7_11h30m,10.55,17.70,24.65,30.47,38.70,46.86,53.78,57.77,72.48
24,0.csv_Day7_12h00m,10.55,19.98,27.04,32.45,41.19,46.20,53.41,66.23,85.21
25,0.csv_Day7_12h30m,13.66,22.60,31.61,35.75,42.32,48.75,60.55,69.16,85.80
26,0.csv_Day7_13h00m,11.27,21.00,27.76,31.41,39.01,44.25,48.75,53.24,69.69
27,0.csv_Day7_13h30m,5.60,11.13,16.30,22.50,26.76,33.34,40.26,46.24,61.08
28,0.csv_Day7_14h00m,6.03,15.04,18.07,23.43,28.68,30.23,34.86,45.24,54.10
29,0.csv_Day7_14h30m,2.56,4.91,10.20,14.77,19.06,23.02,24.11,30.85,39.52
30,0.csv_Day7_15h00m,2.67,6.65,10.78,14.85,17.75,20.63,23.85,30.12,37.26
31,0.csv_Day7_15h30m,2.25,5.74,7.81,12.19,15.57,14.28,20.28,26.55,39.77
32,0.csv_Day7_16h00m,3.07,4.70,7.11,9.69,13.06,13.72,22.85,30.42,53.22
33,0.csv_Day7_16h30m,0.98,2.46,4.59,9.74,14.01,22.13,26.74,38.64,50.10
34,0.csv_Day7_17h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
35,0.csv_Day7_17h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
36,0.csv_Day7_18h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
37,0.csv_Day7_18h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
38,0.csv_Day7_19h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
39,0.csv_Day7_19h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
40,0.csv_Day7_20h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
41,0.csv_Day7_20h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
42,0.csv_Day7_21h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
43,0.csv_Day7_21h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
44,0.csv_Day7_22h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
45,0.csv_Day7_22h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
46,0.csv_Day7_23h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
47,0.csv_Day7_23h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [42]:
submission.iloc[48:96]

,id,q_0.1,q_0.2,q_0.3,q_0.4,q_0.5,q_0.6,q_0.7,q_0.8,q_0.9
48,0.csv_Day8_0h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
49,0.csv_Day8_0h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50,0.csv_Day8_1h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
51,0.csv_Day8_1h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
52,0.csv_Day8_2h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
53,0.csv_Day8_2h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
54,0.csv_Day8_3h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
55,0.csv_Day8_3h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
56,0.csv_Day8_4h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
57,0.csv_Day8_4h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
58,0.csv_Day8_5h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
59,0.csv_Day8_5h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
60,0.csv_Day8_6h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
61,0.csv_Day8_6h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
62,0.csv_Day8_7h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
63,0.csv_Day8_7h30m,0.29,0.83,1.50,2.26,3.92,5.94,10.47,15.05,23.72
64,0.csv_Day8_8h00m,0.31,1.00,1.46,1.78,2.12,2.68,3.83,8.11,15.25
65,0.csv_Day8_8h30m,1.01,2.19,2.66,2.86,3.21,3.56,4.82,6.92,16.72
66,0.csv_Day8_9h00m,1.31,2.89,4.14,4.52,5.16,6.61,8.88,13.24,24.93
67,0.csv_Day8_9h30m,1.81,3.85,5.43,6.21,6.91,8.10,14.00,21.24,28.60
68,0.csv_Day8_10h00m,16.13,25.24,32.92,37.56,45.89,51.14,57.32,72.05,84.80
69,0.csv_Day8_10h30m,14.65,25.33,32.52,40.07,47.76,53.02,60.76,67.48,81.01
70,0.csv_Day8_11h00m,16.15,27.07,33.47,39.31,45.41,53.78,58.88,70.10,81.68
71,0.csv_Day8_11h30m,13.81,22.96,30.64,38.26,44.82,50.11,54.88,64.81,82.63
72,0.csv_Day8_12h00m,12.18,22.23,31.16,39.32,45.96,49.20,54.65,67.53,76.32
73,0.csv_Day8_12h30m,11.79,21.03,26.32,32.84,40.21,47.92,57.70,69.41,82.41
74,0.csv_Day8_13h00m,10.03,13.43,20.30,26.64,34.38,38.09,47.49,57.68,70.35
75,0.csv_Day8_13h30m,4.07,8.92,18.55,28.75,35.43,42.97,53.82,66.72,76.23
76,0.csv_Day8_14h00m,8.90,17.19,26.41,27.51,32.80,36.36,51.60,54.55,63.71
77,0.csv_Day8_14h30m,6.68,11.19,16.64,21.02,29.23,37.50,44.28,41.54,51.70
78,0.csv_Day8_15h00m,4.84,9.21,13.63,16.98,18.57,22.65,23.80,24.92,42.74
79,0.csv_Day8_15h30m,3.95,5.30,11.32,14.24,18.02,19.19,26.24,32.93,45.60
80,0.csv_Day8_16h00m,1.47,3.51,6.94,10.01,14.80,20.60,29.90,34.62,49.35
81,0.csv_Day8_16h30m,1.84,5.09,7.21,14.91,24.25,29.54,35.09,42.30,49.60
82,0.csv_Day8_17h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
83,0.csv_Day8_17h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
84,0.csv_Day8_18h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
85,0.csv_Day8_18h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
86,0.csv_Day8_19h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
87,0.csv_Day8_19h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
88,0.csv_Day8_20h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
89,0.csv_Day8_20h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
90,0.csv_Day8_21h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
91,0.csv_Day8_21h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
92,0.csv_Day8_22h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
93,0.csv_Day8_22h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
94,0.csv_Day8_23h00m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
95,0.csv_Day8_23h30m,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [43]:
submission.to_csv('./data/only_GHI.csv', index=False)